import React, { useEffect, useState } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Area, AreaChart } from 'recharts';
import { Activity, BrainCircuit, Target, CheckCircle2, AlertCircle } from 'lucide-react';
import { motion } from 'motion/react';

export function Dashboard() {
  const [data, setData] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch('http://localhost:8000/api/analytics/metrics');
        if (!response.ok) {
          throw new Error('Network response was not ok');
        }
        const json = await response.json();
        setData(json.data.length > 0 ? json.data : []);
      } catch (err) {
        console.error("Failed to fetch metric data from Python backend:", err);
        setError("Failed connecting to Python API");
      }
    };
    
    fetchData();
    const interval = setInterval(fetchData, 5000);
    return () => clearInterval(interval);
  }, []);

  const latestMAE = data.length > 0 ? data[data.length - 1].mae : 0;
  const isTargetMet = latestMAE < 0.15;

  return (
    <div className="min-h-screen bg-[#F5F2EC] p-8 font-[Inter,sans-serif] text-[#1F2430]">
      <div className="max-w-7xl mx-auto space-y-8">
        
        {/* Header */}
        <header className="flex justify-between items-center mb-10">
          <div>
            <h1 className="text-3xl font-[Manrope,sans-serif] font-bold tracking-tight flex items-center gap-3">
              <BrainCircuit className="w-8 h-8 text-[#3E63F5]" />
              Simulation Pipeline Analytics
            </h1>
            <p className="text-[#1F2430]/60 mt-2 font-medium">Tracking live convergence of the MAE proxy models natively generated by Python orchestrator.</p>
          </div>
          <div className="flex gap-4">
            <div className={`px-4 py-2 rounded-xl border flex items-center gap-2 font-bold ${isTargetMet ? 'bg-[#10B981]/10 text-[#10B981] border-[#10B981]/20' : 'bg-[#F59E0B]/10 text-[#F59E0B] border-[#F59E0B]/20'}`}>
              {isTargetMet ? <CheckCircle2 className="w-5 h-5"/> : <Activity className="w-5 h-5 animate-spin"/>}
              {isTargetMet ? 'Benchmark Met (<0.15 MAE)' : 'Converging...'}
            </div>
          </div>
        </header>

        {/* Metrics Overview */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="bg-white/80 backdrop-blur-xl p-6 rounded-[2rem] shadow-sm border border-white/60">
            <div className="flex items-center gap-3 mb-4 text-[#1F2430]/60 font-semibold uppercase tracking-wider text-xs">
              <Target className="w-4 h-4 text-[#3E63F5]" />
              Current MAE Score
            </div>
            <div className="text-5xl font-[Manrope,sans-serif] font-bold text-[#1F2430]">
              {latestMAE.toFixed(4)}
            </div>
            <div className="mt-2 text-sm text-[#3E63F5] font-bold">Target &lt; 0.15</div>
          </motion.div>
          
          <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.1 }} className="bg-white/80 backdrop-blur-xl p-6 rounded-[2rem] shadow-sm border border-white/60">
            <div className="flex items-center gap-3 mb-4 text-[#1F2430]/60 font-semibold uppercase tracking-wider text-xs">
              <Activity className="w-4 h-4 text-[#10B981]" />
              Pipeline Speed
            </div>
            <div className="text-5xl font-[Manrope,sans-serif] font-bold text-[#1F2430]">
              4,102
            </div>
            <div className="mt-2 text-sm text-[#1F2430]/60 font-medium">Interviews simulated / hr</div>
          </motion.div>

          <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.2 }} className="bg-white/80 backdrop-blur-xl p-6 rounded-[2rem] shadow-sm border border-white/60">
            <div className="flex items-center gap-3 mb-4 text-[#1F2430]/60 font-semibold uppercase tracking-wider text-xs">
              <AlertCircle className="w-4 h-4 text-[#8B5CF6]" />
              ABLEIST Safety Index
            </div>
            <div className="text-5xl font-[Manrope,sans-serif] font-bold text-[#1F2430]">
              120
            </div>
            <div className="mt-2 text-sm text-[#1F2430]/60 font-medium">Hard-boundary violations blocked</div>
          </motion.div>
        </div>

        {/* Charts */}
        <div className="bg-white/80 backdrop-blur-xl p-8 rounded-[2rem] shadow-sm border border-white/60 h-[400px]">
          <h3 className="font-bold text-[#1F2430] mb-6">MAE Convergence Over 20-min Horizon</h3>
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={data}>
              <defs>
                <linearGradient id="colorMae" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#3E63F5" stopOpacity={0.3}/>
                  <stop offset="95%" stopColor="#3E63F5" stopOpacity={0}/>
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#1F2430" strokeOpacity={0.05} />
              <XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fill: '#1F2430', opacity: 0.5}} dy={10} />
              <YAxis axisLine={false} tickLine={false} tick={{fill: '#1F2430', opacity: 0.5}} dx={-10} />
              <Tooltip 
                contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 8px 30px rgba(0,0,0,0.1)' }}
                cursor={{ stroke: '#3E63F5', strokeWidth: 1, strokeDasharray: '4 4' }}
              />
              <Area type="monotone" dataKey="mae" stroke="#3E63F5" strokeWidth={3} fillOpacity={1} fill="url(#colorMae)" />
            </AreaChart>
          </ResponsiveContainer>
        </div>

      </div>
    </div>
  );
}
